### PR TITLE
Added a welcome page with few more small changes

### PR DESCRIPTION
**Pull request by TotoWang-hhh**
- Added a welcome page (which is still under cunstruction).
- Moved original index.html to boot.html.
- Rewrote part of the js code about password validating.
- Fixed the empty line in the middle of the two parts of settings ui (The color of the separator still needs to be confirmed and adjusted).

Please merge ASAP, better before your next update, to prevent any conflicts for my future actions.

### CODE REVIEW

**Comment by TotoWang-hhh** [comment]
And, consider gving me and micropue write permissions to this repo?

**Comment by TotoWang-hhh** [comment]
I've changed the new (bata) version branch, and moved it to the main. The old stuff are moved to the `old` branch. By this, GitHub Pages should be able to build depending on the latest code.

**Comment by TotoWang-hhh** [comment]
I think I have already checked if there is any conflicts or duplicates between new and old codes, but I'm not quite sure if everything is going as planned. I think you may have to chech everything again because you wrote the most of the code, and of course, know more about that.

**Comment by CodeCrafter-TL** [comment]
Your work is excellent! But I think you can remove the old files at once, and put them in the old branch

**Comment by CodeCrafter-TL** [comment]
What do you think? Should I finish this work, or should you do it yourself?

**Comment by CodeCrafter-TL** [comment]
I can merge this pull request now and address these tasks in the future.

**Pull request merged**
